version: '3.8'

services:
  db:
    image: postgres:15
    container_name: coursework_db
    environment:
      POSTGRES_DB: cosmetics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Uc~FXtxYWP
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cosmetics"]
      interval: 5s
      timeout: 5s
      retries: 10

  loader:
    build: .
    container_name: csv_loader
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:Uc~FXtxYWP@db:5432/cosmetics
    volumes:
      - .:/app
    command: ["python", "dbConnect.py"]

  app:
    build: .
    container_name: coursework_app
    depends_on:
      loader:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:Uc~FXtxYWP@db:5432/cosmetics

volumes:
  postgres_data: